server:
  port: 8088

spring:
  application:
    name: banking
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/BankDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:175003}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 300000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

jwt:
  expiration: 2592000

security:
  keystore:
    location: classpath:keystore/keystore.p12
    password: ${PASSWORD_RSA:l3lackcl0ver}
    alias: jwt-rsa
  aes:
    key: ${AES_KEY:v3UoX5VzK8lT4pQ9rS2mN6yJ1wB0eA7dF4gH8jK9lM0=}
    algorithm: AES/GCM/NoPadding
    tag-length: 128
    iv-length: 12